version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017

  account-container:
    container_name: ecommcpv-account
    build: ./accounts/
    environment:
      MONGO_DATABASE: mongodb://admin:secret@mongodb:27017/ecomm-account?authSource=admin
    volumes:
      - ./accounts/:/app/accounts
    ports:
      - 8001:8001
    depends_on:
      - mongodb

  anti-fraud-container:
    container_name: ecommcpv-anti-fraud
    build: ./anti-fraud/
    environment:
      MONGO_DATABASE: mongodb://admin:secret@mongodb:27017/ecomm-anti-fraud?authSource=admin
    volumes:
      - ./anti-fraud/:/app/anti-fraud
    ports:
      - 8002:8002
    depends_on:
      - mongodb

  transactions-container:
    container_name: ecommcpv-transactions
    build: ./transactions/
    environment:
      MONGO_DATABASE: mongodb://admin:secret@mongodb:27017/ecomm-transactions?authSource=admin
    volumes:
      - ./transactions/:/app/transactions

    ports:
      - 8003:8003
    depends_on:
      - mongodb

volumes:
  mongodb: