version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongoDB
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    
  account-container:
    container_name: ecommcpv-account
    build: ./accounts/
    volumes:
      - ./accounts/:/app/accounts
    environment:
      MONGO_ACCOUNT_URL: "mongodb://admin:secret@mongodb:27017/ecomm-account?authSource=admin"
    ports:
      - 8001:8001
    depends_on:
      - mongodb

volumes:
  mongodb: