version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongoDB
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017

  anti-fraud-container:
    container_name: ecommcpv-anti-fraud
    build: ./anti-fraud/
    environment:
      MONGO_ACCOUNT_HOST: "mongodb"
      MONGO_ACCOUNT_USER: "admin"
      MONGO_ACCOUNT_PASSWORD: "secret"
      MONGO_DATABASE: "ecomm-anti-fraud"
      MONGO_ACCOUNT_PORT: 27017
    volumes:
      - ./anti-fraud/:/app/anti-fraud
    ports:
      - 8002:8002
    depends_on:
      - mongodb

volumes:
  mongodb: