name: Lint

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build the Docker image
        run: docker-compose build
      - name: ESLint Code Review
        uses: yousufkalim/eslint-action@latest
        with:
          eslint-args: '--ignore-path=.gitignore'
          eslintrc: true # Set this to true if you want to use your own .eslintrc rules
          extensions: 'js,jsx,ts,tsx'
          auto-auto-fix-before-test: false # Set this to true if want to format and fix all the lint issue before testing
          annotations: true